version: "3.9"
networks:
  my_network:
    driver: bridge
volumes:
  mysql-data:
services:
  mysql0: 
    image: mysql:8.0
    container_name: nhloc-db
    environment:
       MYSQL_ROOT_PASSWORD: ""
       MYSQL_ALLOW_EMPTY_PASSWORD: "true"  
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/data/db


