version: "3.9"
networks:
  my_network:
    driver: bridge
volumes:
  mysql-data:
services:
  mysql0:
    image: mysql:8.0
    container_name: nhloc-db
    environment:
       MYSQL_ROOT_PASSWORD: 
       MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/data/db
  # zookeeper-1:
  #   hostname: zookeeper-1
  #   container_name: zookeeper-1
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181
  # kafka-1:
  #   hostname: kafka-1
  #   container_name: kafka-1
  #   image: confluentinc/cp-kafka:7.2.1
  #   depends_on:
  #     - zookeeper-1
  #   ports:
  #     - 29092:29092
  #     - 9997:9997
  #     - 9092:9092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_JMX_PORT: 9997
  #     KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schemaregistry:8085
  #     CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-1:29092
  # schemaregistry:
  #   hostname: schemaregistry-1
  #   container_name: schemaregistry-1
  #   image: confluentinc/cp-schema-registry:7.2.1
  #   ports:
  #     - 8085:8085
  #   depends_on:
  #     - kafka-1
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:29092
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:2181
  #     SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
  #     SCHEMA_REGISTRY_HOST_NAME: schemaregistry-1
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
  #     SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: http
  #     SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
  #     SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
  # kafka-ui-1:
  #   container_name: kafka-ui-1
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - zookeeper-1
  #     - kafka-1
  #     - schemaregistry
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: cluster_0
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 127.0.0.1:29092
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181
  #     KAFKA_CLUSTERS_0_JMXPORT: 9997
  #     KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085




