version: "3.9"
networks:
  my_network:
    driver: bridge
services:
  mongo0: 
    image: mongo:4.4.10
    container_name: nhloc-db
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:

