name: Deploy Monorepo Apps

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - production

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.export_env.outputs.env_vars }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate JSON Configuration Files
        id: export_env
        run: |
          mkdir -p config
          echo '${{ vars.CONFIG_ACCOUNT }}' > config/account.json
          echo '${{ vars.CONFIG_ADMIN }}' > config/admin.json
          echo '${{ vars.CONFIG_RENTAL_CLIENT }}' > config/rental-client.json
          echo '${{ vars.CONFIG_SERVICE }}' > config/service.json

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install


      - name: Link JSON file
        run: pnpm link-env
      
      - name: build
        run: pnpm build